// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"GAMERS-BE/internal/common/security/password"
	"GAMERS-BE/internal/user/application"
	"GAMERS-BE/internal/user/infra/persistence/command"
	"GAMERS-BE/internal/user/infra/persistence/query"
	"GAMERS-BE/internal/user/presentation"
	"gorm.io/gorm"
)

// Injectors from wire.go:

// InitializeUserController creates UserController with all dependencies
func InitializeUserController(db *gorm.DB) *presentation.UserController {
	mysqlUserRepository := query.NewMysqlUserRepository(db)
	mySQLUserRepository := command.NewMySQLUserRepository(db)
	mysqlProfileCommandAdapter := command.NewMysqlProfileCommandAdapter(db)
	bcryptPasswordHasher := password.NewBcryptPasswordHasher()
	userService := application.NewUserService(mysqlUserRepository, mySQLUserRepository, mysqlProfileCommandAdapter, bcryptPasswordHasher)
	userController := presentation.NewUserController(userService)
	return userController
}

// InitializeProfileController creates ProfileController with all dependencies
func InitializeProfileController(db *gorm.DB) *presentation.ProfileController {
	mysqlProfileQueryAdapter := query.NewMysqlProfileQueryAdapter(db)
	mysqlProfileCommandAdapter := command.NewMysqlProfileCommandAdapter(db)
	profileService := application.NewProfileService(mysqlProfileQueryAdapter, mysqlProfileCommandAdapter)
	profileController := presentation.NewProfileController(profileService)
	return profileController
}
