package exception

import (
	"net/http"
)

var (
	ErrContestNotFound            = NewBusinessError(http.StatusNotFound, "contest not found", "CT001")
	ErrInvalidStatusTransition    = NewBusinessError(http.StatusConflict, "invalid contest status transition", "CT002")
	ErrContestMemberNotFound      = NewBusinessError(http.StatusNotFound, "contest member not found", "CT003")
	ErrUserNotExists              = NewBusinessError(http.StatusNotFound, "user or invitation not found", "CT004")
	ErrContestAlreadyExists       = NewBusinessError(http.StatusConflict, "contest already exists", "CT005")
	ErrContestNoChanges           = NewBadRequestError("contest has no changes", "CT006")
	ErrInvalidContestDates        = NewBadRequestError("contest start date must be before end date", "CT007")
	ErrInvalidContestType         = NewBadRequestError("invalid contest type", "CT008")
	ErrInvalidContestStatus       = NewBadRequestError("invalid contest status", "CT009")
	ErrInvalidMaxTeamCount        = NewBadRequestError("max team count must be positive", "CT010")
	ErrInvalidTotalPoint          = NewBadRequestError("total point must be non-negative", "CT011")
	ErrInvalidContestTitle        = NewBadRequestError("contest title is required", "CT012")
	ErrInvalidUserID              = NewBadRequestError("invalid user id", "CT013")
	ErrInvalidContestID           = NewBadRequestError("invalid contest id", "CT014")
	ErrInvalidMemberType          = NewBadRequestError("invalid member type", "CT015")
	ErrInvalidLeaderType          = NewBadRequestError("invalid leader type", "CT016")
	ErrInvalidPoint               = NewBadRequestError("point must be non-negative", "CT017")
	ErrAlreadyContestMemberExists = NewBusinessError(http.StatusConflict, "contest member already exists", "CT018")
	ErrAlreadyApplied             = NewBusinessError(http.StatusConflict, "already applied to this contest", "CT019")
	ErrApplicationNotPending      = NewBadRequestError("application is not pending", "CT020")
	ErrApplicationNotFound        = NewNotFoundError("application not found", "CT021")
	ErrCannotAcceptApplication    = NewBadRequestError("contest is not accepting applications", "CT022")
	ErrInvalidAccess              = NewBusinessError(http.StatusForbidden, "you are not a member of this contest", "CT024")
	ErrContestAlreadyStarted      = NewBusinessError(http.StatusForbidden, "only contest leader can perform this action", "CT025")
	ErrContestNotPending          = NewBadRequestError("contest is not in pending status", "CT026")
	ErrContestCannotStart         = NewBadRequestError("contest start time has not arrived yet", "CT027")
	ErrDiscordTextChannelRequired = NewBadRequestError("discord text channel id is required when guild id is provided", "CT028")
	ErrLeaderCannotWithdraw       = NewBusinessError(http.StatusForbidden, "leader cannot withdraw from contest", "CT029")
	ErrInvalidTotalTeamMember     = NewBadRequestError("total team member must be at least 1", "CT030")
	ErrInvalidGameType            = NewBadRequestError("invalid game type", "CT031")
	ErrContestNotActive           = NewBadRequestError("contest is not in active status", "CT032")
)
